version: "3"
services:
  server:
    build:
      context: ./basic-calculator-rest
      dockerfile: Dockerfile
    image: misahael/basic-calculator-server:latest
    expose:
      - ${APP_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}

  client:
    build: ./basic-calculator
    environment:
      - APP_CLIENT_PORT=${APP_CLIENT_PORT}
    expose:
      - 80
    ports:
      - 8081:80
    links:
      - server
